set_property SRC_FILE_INFO {cfile:/home/kokunev/data/git_root/laser_board_xdma_plus_ddr/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/source/design_1_xdma_0_0_pcie2_ip-PCIE_X0Y0.xdc rfile:../../../project_1.gen/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/source/design_1_xdma_0_0_pcie2_ip-PCIE_X0Y0.xdc id:1 order:EARLY scoped_inst:inst/design_1_xdma_0_0_pcie2_to_pcie3_wrapper_i/pcie2_ip_i/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/kokunev/data/git_root/laser_board_xdma_plus_ddr/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_xdma_0_0/source/design_1_xdma_0_0_pcie3_7vx_ip.xdc rfile:../../../project_1.gen/sources_1/bd/design_1/ip/design_1_xdma_0_0/source/design_1_xdma_0_0_pcie3_7vx_ip.xdc id:2 order:EARLY scoped_inst:inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/kokunev/data/git_root/laser_board_xdma_plus_ddr/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/source/ip_xilinx_pcie_2_1_7x_late.xdc rfile:../../../project_1.gen/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/source/ip_xilinx_pcie_2_1_7x_late.xdc id:3 order:LATE scoped_inst:inst/design_1_xdma_0_0_pcie2_to_pcie3_wrapper_i/pcie2_ip_i/inst} [current_design]
current_instance inst/design_1_xdma_0_0_pcie2_to_pcie3_wrapper_i/pcie2_ip_i/inst
set_property src_info {type:SCOPED_XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTPE2_CHANNEL_X0Y7 [get_cells {inst/gt_top_i/pipe_wrapper_i/pipe_lane[0].gt_wrapper_i/gtp_channel.gtpe2_channel_i}]
set_property src_info {type:SCOPED_XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTPE2_CHANNEL_X0Y6 [get_cells {inst/gt_top_i/pipe_wrapper_i/pipe_lane[1].gt_wrapper_i/gtp_channel.gtpe2_channel_i}]
set_property src_info {type:SCOPED_XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTPE2_COMMON_X0Y1 [get_cells {inst/gt_top_i/pipe_wrapper_i/pipe_lane[0].pipe_quad.gt_common_enabled.gt_common_int.gt_common_i/qpll_wrapper_i/gtp_common.gtpe2_common_i}]
set_property src_info {type:SCOPED_XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PCIE_X0Y0 [get_cells inst/pcie_top_i/pcie_7x_i/pcie_block_i]
set_property src_info {type:SCOPED_XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X2Y36 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_rx/brams[3].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:SCOPED_XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X1Y37 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_rx/brams[2].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:SCOPED_XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X1Y36 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_rx/brams[1].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:SCOPED_XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X1Y35 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_rx/brams[0].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:SCOPED_XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X1Y34 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_tx/brams[0].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:SCOPED_XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X1Y33 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_tx/brams[1].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:SCOPED_XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X1Y32 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_tx/brams[2].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:SCOPED_XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X1Y31 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_tx/brams[3].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
current_instance
current_instance inst
set_property src_info {type:SCOPED_XDC file:2 line:117 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type DRC -id {REQP-1839} -tags "1166691" -user "xdma" -internal -scope -desc "DRC expects synchronous pins to be provided to BRAM inputs. Since synchronization is present one stage before, it is safe to ignore" -objects [list [get_cells -hierarchical -filter {NAME =~ {*pcie2_to_pcie3_wrapper_i/*dma_cpl_fifo_inst/U0/*.WIDE_PRIM36_NO_ECC.ram}}] [get_cells -hierarchical -filter {NAME =~ {*udma_wrapper/dma_top/*_nn1_reg*} && PRIMITIVE_TYPE =~ {*BRAM*}}]]
set_property src_info {type:SCOPED_XDC file:2 line:119 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type DRC -id {REQP-1840} -tags "1166691" -user "xdma" -internal -scope -desc "DRC expects synchronous pins to be provided to BRAM inputs. Since synchronization is present one stage before, it is safe to ignore" -objects [list [get_cells -hierarchical -filter {NAME =~ {*pcie2_to_pcie3_wrapper_i/*dma_cpl_fifo_inst/U0/*.WIDE_PRIM18.ram}}] [get_cells -hierarchical -filter {NAME =~ {*udma_wrapper/dma_top/*_nn1_reg*} && PRIMITIVE_TYPE =~ {*BRAM*}}]]
set_property src_info {type:SCOPED_XDC file:2 line:122 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type DRC -id {REQP-1839} -tags "1166691" -user "xdma" -internal -scope -desc "DRC expects synchronous pins to be provided to BRAM inputs. Since synchronization is present one stage before, it is safe to ignore" -objects [list [get_cells -hierarchical -filter {NAME =~ {*ram_top/*_PCIE_DSC_CPLD_RAM/the_bram_reg_*} && PRIMITIVE_TYPE =~ {*BRAM*}}] [get_cells -hierarchical -filter {NAME =~ {*ram_top/MASTER_READ_BRAM/*.mem_reg*} && PRIMITIVE_TYPE =~ {*BRAM*}}] [get_cells -hierarchical -filter {NAME =~ {*ram_top/mas_bridge_ram_write_512.MASTER*.mem_reg*} && PRIMITIVE_TYPE =~ {*BRAM*}}] [get_cells -hierarchical -filter {NAME =~ {*ram_top/*_DAT*_FIFO/*.mem_reg*} && PRIMITIVE_TYPE =~ {*BRAM*}}]]
set_property src_info {type:SCOPED_XDC file:2 line:124 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type DRC -id {REQP-1840} -tags "1166691" -user "xdma" -internal -scope -desc "DRC expects synchronous pins to be provided to BRAM inputs. Since synchronization is present one stage before, it is safe to ignore" -objects [list [get_cells -hierarchical -filter {NAME =~ {*ram_top/*_DAT*_FIFO/*.mem_reg*} && PRIMITIVE_TYPE =~ {*BRAM*}}] [get_cells -hierarchical -filter {NAME =~ {*ram_top/*_WRITE_FIFO/*.mem_reg*} && PRIMITIVE_TYPE =~ {*BRAM*}}]]
current_instance
current_instance inst/design_1_xdma_0_0_pcie2_to_pcie3_wrapper_i/pcie2_ip_i/inst
set_property src_info {type:SCOPED_XDC file:3 line:78 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id CDC-1 -user "pcie_7x" -tags "1165856" -desc "async sys_reset - safe to ignore" -scope -internal -to [get_pins -hier -filter {SCOPED_NAME =~ {inst/pl_phy_lnk_up_q_reg/R}}]
set_property src_info {type:SCOPED_XDC file:3 line:79 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id CDC-1 -user "pcie_7x" -tags "1165856" -desc "async sys_reset - safe to ignore" -scope -internal -to [get_pins -hier -filter {SCOPED_NAME =~ {inst/user_lnk_up_int_reg/R}}]
set_property src_info {type:SCOPED_XDC file:3 line:80 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id CDC-1 -user "pcie_7x" -tags "1165856" -desc "async sys_reset - safe to ignore" -scope -internal -to [get_pins -hier -filter {SCOPED_NAME =~ {inst/pl_received_hot_rst_q_reg/R}}]
set_property src_info {type:SCOPED_XDC file:3 line:82 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id CDC-7 -user "pcie_7x" -tags "1165856" -desc "async sys_reset - safe to ignore" -scope -internal -to [get_pins -hier -filter {SCOPED_NAME =~ {inst/user_reset_int_reg/PRE}}]
set_property src_info {type:SCOPED_XDC file:3 line:83 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id CDC-1 -user "pcie_7x" -tags "1165856" -desc "async sys_reset - safe to ignore" -scope -internal -to [get_pins -hier -filter {SCOPED_NAME =~ {inst/user_lnk_up_mux_reg/R}}]
