set_property SRC_FILE_INFO {cfile:/home/kokunev/data/git_root/laser_board_xdma_plus_ddr/project_1/project_1.srcs/constrs_1/new/io.xdc rfile:../../../project_1.srcs/constrs_1/new/io.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F6 [get_ports {pcie_clk_clk_p[0]}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H13 [get_ports pcie_reset_n]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B8 [get_ports {pcie_mgt_0_rxp[0]}]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D11 [get_ports {pcie_mgt_0_rxp[1]}]
